import Navbar from "@/components/navbar";
import React from "react";
import "./globals.css";
import { Inter } from "next/font/google";

import { getServerSession } from "next-auth";
import { authOptions } from "@/libs/auth";
import { NextAuthProvider } from "./providers";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  if (!session) {
    redirect("/api/auth/signin");
  }

  return (
    <html lang="en" className="dark">
      <body>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
